# Form implementation generated from reading ui file 'baihat.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import *
from PyQt6.QtGui import *
import pygame




class baihat(QWidget):
    def __init__(self,TenBaiHat,TacGia,ThoiLuong,TenHinh,mp3):
        super().__init__()
        self.TenBaiHat=TenBaiHat
        self.TacGia=TacGia
        self.ThoiLuong=ThoiLuong
        self.TenHinh=TenHinh
        self.mp3=mp3
        self.setUi()
    def setUi(self):
        self.resize(585, 94)
        self.frame = QtWidgets.QFrame(self)
        self.frame.setGeometry(QtCore.QRect(10, 10, 571, 80))
        self.frame.setStyleSheet("background-color: rgb(112, 66, 100);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.lblHinh = QtWidgets.QLabel(parent=self.frame)
        self.lblHinh.setGeometry(QtCore.QRect(0, 10, 61, 61))
        self.lblHinh.setText("")
        
        self.lblHinh.setObjectName("lblHinh")
        self.lblTenBaiHat = QtWidgets.QLabel(parent=self.frame)
        self.lblTenBaiHat.setGeometry(QtCore.QRect(70, 20, 111, 16))
        self.lblTenBaiHat.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblTenBaiHat.setObjectName("lblTenBaiHat")
        self.lblTacGia = QtWidgets.QLabel(parent=self.frame)
        self.lblTacGia.setGeometry(QtCore.QRect(70, 40, 111, 16))
        self.lblTacGia.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblTacGia.setObjectName("lblTacGia")
        self.lblThoiLuong = QtWidgets.QLabel(parent=self.frame)
        self.lblThoiLuong.setGeometry(QtCore.QRect(200, 30, 31, 16))
        self.lblThoiLuong.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblThoiLuong.setObjectName("lblThoiLuong")
        self.btnPlay = QtWidgets.QPushButton(parent=self.frame)
        self.btnPlay.setGeometry(QtCore.QRect(310, 10, 51, 61))
        self.btnPlay.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("TienNuClient/imgs/icons8-play-button-circled-24.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnPlay.setIcon(icon)
        self.btnPlay.setIconSize(QtCore.QSize(50, 50))
        self.btnPlay.setObjectName("btnPlay")
        self.btnPlay.clicked.connect(self.playSong)
        
        self.btnPlayList = QtWidgets.QPushButton(parent=self.frame)
        self.btnPlayList.setGeometry(QtCore.QRect(390, 10, 51, 61))
        self.btnPlayList.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("TienNuClient/imgs/icons8-playlist-30.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnPlayList.setIcon(icon1)
        self.btnPlayList.setIconSize(QtCore.QSize(50, 50))
        self.btnPlayList.setObjectName("btnPlayList")
        self.btnLike = QtWidgets.QPushButton(parent=self.frame)
        self.btnLike.setGeometry(QtCore.QRect(460, 10, 51, 61))
        self.btnLike.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("TienNuClient/imgs/icons8-favorite-24 (1).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnLike.setIcon(icon2)
        self.btnLike.setIconSize(QtCore.QSize(50, 50))
        self.btnLike.setObjectName("btnLike")

        self.retranslateUi()

    def retranslateUi(self):
        self.lblTenBaiHat.setText(str(self.TenBaiHat))
        self.lblTacGia.setText(str(self.TacGia))
        self.lblThoiLuong.setText(str(self.ThoiLuong))
        self.lblHinh.setPixmap(QtGui.QPixmap.fromImage(QtGui.QImage("TienNuClient/imgs/" + self.TenHinh)))
        self.lblHinh.setScaledContents(True)

    def playSong(self):
                # self.btnStop.setVisible(True)
                pygame.mixer.init()

                songPath = "TienNuClient/song/" +self.mp3
                pygame.mixer.stop()
                try:
            # Load the song using pygame mixer
                        song = pygame.mixer.Sound(songPath)
                        song.play()
                        self.btnPlay.clicked.connect(self.stopPlaySong)
                except Exception as e:
                        QMessageBox.information(None, "Thông báo!", "Lỗi khi phát nhạc!")
                        # self.btnStop.setVisible(False)

    def stopPlaySong(self):
                # self.btnStop.setVisible(False)
                pygame.mixer.stop()
                self.btnPlay.clicked.connect(self.playSong)

if __name__ == "__main__":
    bh=baihat()

