# Form implementation generated from reading ui file 'dangky.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import *
from PyQt6.QtGui import *
from PyQt6.QtCore import *
import UserBUS
import User
from datetime import datetime
from GetDataFromServer import GetDataFromServer
class dangky(QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi()
    def setupUi(self):
        self.resize(400, 300)
        self.frame = QtWidgets.QFrame(parent=self)
        self.frame.setGeometry(QtCore.QRect(30, 20, 381, 261))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.lblTitle = QtWidgets.QLabel(parent=self.frame)
        self.lblTitle.setGeometry(QtCore.QRect(100, 0, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lblTitle.setFont(font)
        self.lblTitle.setObjectName("lblTitle")
        self.txtUsername = QtWidgets.QLineEdit(parent=self.frame)
        self.txtUsername.setGeometry(QtCore.QRect(110, 60, 231, 22))
        self.txtUsername.setObjectName("txtUsername")
        self.txtConfirmPassword = QtWidgets.QLineEdit(parent=self.frame)
        self.txtConfirmPassword.setGeometry(QtCore.QRect(110, 180, 231, 22))
        self.txtConfirmPassword.setText("")
        self.txtConfirmPassword.setObjectName("txtConfirmPassword")
        self.txtTenTaiKhoan = QtWidgets.QLineEdit(parent=self.frame)
        self.txtTenTaiKhoan.setGeometry(QtCore.QRect(110, 100, 231, 22))
        self.txtTenTaiKhoan.setObjectName("txtTenTaiKhoan")
        self.lblConfirmPassword = QtWidgets.QLabel(parent=self.frame)
        self.lblConfirmPassword.setGeometry(QtCore.QRect(0, 180, 101, 20))
        self.lblConfirmPassword.setObjectName("lblConfirmPassword")
        self.lblName = QtWidgets.QLabel(parent=self.frame)
        self.lblName.setGeometry(QtCore.QRect(0, 60, 81, 20))
        self.lblName.setObjectName("lblName")
        self.lblUsername = QtWidgets.QLabel(parent=self.frame)
        self.lblUsername.setGeometry(QtCore.QRect(0, 100, 71, 20))
        self.lblUsername.setObjectName("lblUsername")
        self.lblPassword = QtWidgets.QLabel(parent=self.frame)
        self.lblPassword.setGeometry(QtCore.QRect(0, 140, 51, 20))
        self.lblPassword.setObjectName("lblPassword")
        self.txtPassword = QtWidgets.QLineEdit(parent=self.frame)
        self.txtPassword.setGeometry(QtCore.QRect(110, 140, 231, 22))
        self.txtPassword.setText("")
        self.txtPassword.setObjectName("txtPassword")
        self.btnDangNhap = QtWidgets.QPushButton(parent=self.frame)
        self.btnDangNhap.setGeometry(QtCore.QRect(250, 220, 75, 24))
        self.btnDangNhap.setObjectName("btnDangNhap")
        self.btnDangKy = QtWidgets.QPushButton(parent=self.frame)
        self.btnDangKy.setGeometry(QtCore.QRect(30, 220, 75, 24))
        self.btnDangKy.setStyleSheet("color: rgb(0, 0, 255);")
        self.btnDangKy.setObjectName("btnDangKy")
        self.btnDangKy.clicked.connect(self.CreateDangKy)

        self.retranslateUi()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.lblTitle.setText(_translate("Form", "ĐĂNG KÝ"))
        self.lblConfirmPassword.setText(_translate("Form", "Nhập lại mật khẩu"))
        self.lblName.setText(_translate("Form", "Tên đăng nhập"))
        self.lblUsername.setText(_translate("Form", "Tên tài khoản"))
        self.lblPassword.setText(_translate("Form", "Mật khẩu"))
        self.btnDangNhap.setText(_translate("Form", "Đăng nhập"))
        self.btnDangKy.setText(_translate("Form", "Đăng ký"))

    def CreateDangKy(self):
        if(self.txtPassword.text() != self.txtConfirmPassword.text()):
            QMessageBox.critical(self, "Error", "Passwords do not match.")
        else:
            QMessageBox.information(self, "Success", "Passwords match.")
            client = GetDataFromServer()
            client.connect()
            username=self.txtUsername.text()
            password=self.txtPassword.text()
            name=self.txtTenTaiKhoan.text()
            # ngay_hien_tai = datetime.now()
            # datecreate= ngay_hien_tai.strftime('%Y-%m-%d')
            print (username + " "+ password + " "+name)
            receive = client.sendAddUser("ADD_TO_USER_" + name + "_" + username+ "_" + password)
            print(receive)
        
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = dangky()
    ui.show()
    sys.exit(app.exec())
