# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(802, 590)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imgs/chidep.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.menuPanel = QtWidgets.QFrame(parent=self.centralwidget)
        self.menuPanel.setGeometry(QtCore.QRect(0, 0, 201, 591))
        self.menuPanel.setStyleSheet("background-color: #092635;")
        self.menuPanel.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.menuPanel.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.menuPanel.setObjectName("menuPanel")
        self.appName = QtWidgets.QLabel(parent=self.menuPanel)
        self.appName.setGeometry(QtCore.QRect(60, 30, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.appName.setFont(font)
        self.appName.setStyleSheet("color: #9EC8B9;")
        self.appName.setObjectName("appName")
        self.txtSearch = QtWidgets.QLineEdit(parent=self.menuPanel)
        self.txtSearch.setGeometry(QtCore.QRect(30, 60, 141, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.txtSearch.setFont(font)
        self.txtSearch.setStyleSheet("background-color: #9EC8B9;")
        self.txtSearch.setObjectName("txtSearch")
        self.btnTrangChu = QtWidgets.QPushButton(parent=self.menuPanel)
        self.btnTrangChu.setGeometry(QtCore.QRect(20, 130, 151, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnTrangChu.setFont(font)
        self.btnTrangChu.setStyleSheet("color: #9EC8B9;")
        self.btnTrangChu.setObjectName("btnTrangChu")
        self.btnTrangChu_2 = QtWidgets.QPushButton(parent=self.menuPanel)
        self.btnTrangChu_2.setGeometry(QtCore.QRect(20, 180, 151, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnTrangChu_2.setFont(font)
        self.btnTrangChu_2.setStyleSheet("color: #9EC8B9;")
        self.btnTrangChu_2.setObjectName("btnTrangChu_2")
        self.btnTrangChu_3 = QtWidgets.QPushButton(parent=self.menuPanel)
        self.btnTrangChu_3.setGeometry(QtCore.QRect(20, 230, 151, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnTrangChu_3.setFont(font)
        self.btnTrangChu_3.setStyleSheet("color: #9EC8B9;")
        self.btnTrangChu_3.setObjectName("btnTrangChu_3")
        self.label = QtWidgets.QLabel(parent=self.menuPanel)
        self.label.setGeometry(QtCore.QRect(20, 20, 31, 31))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("imgs/chidep-icon.jpg"))
        self.label.setObjectName("label")
        self.musicPanel = QtWidgets.QFrame(parent=self.centralwidget)
        self.musicPanel.setGeometry(QtCore.QRect(199, -1, 611, 591))
        self.musicPanel.setStyleSheet("background-color: #ffffff;")
        self.musicPanel.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.musicPanel.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.musicPanel.setObjectName("musicPanel")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chị Đẹp MP3"))
        self.appName.setText(_translate("MainWindow", "Chị Đẹp MP3"))
        self.btnTrangChu.setText(_translate("MainWindow", "Trang chủ"))
        self.btnTrangChu_2.setText(_translate("MainWindow", "PlayList"))
        self.btnTrangChu_3.setText(_translate("MainWindow", "Yêu thích"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
