# Form implementation generated from reading ui file 'playlist_GUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import *
from PyQt6.QtGui import *
import pygame
import baihat
from GetDataFromServer import GetDataFromServer
class Favorite_GUI(QWidget):
    def __init__(self,userIDDemo):
        super().__init__()
        self.userIDDemo=userIDDemo
        print(userIDDemo)
        self.setUi()
    def setUi(self):
        self.setObjectName("Form")
        self.resize(611, 591)

        self.scrollArea = QtWidgets.QScrollArea(parent=self)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 611, 591))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 609, 589))
        self.layout = QGridLayout()
        self.layout.setHorizontalSpacing(0)
        self.layout.setVerticalSpacing(0)
        self.scrollAreaWidgetContents.setLayout(self.layout)
        self.getFavorite()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        
        self.retranslateUi()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))

    def getFavorite(self):
        userIDDemoa = str(self.userIDDemo)  # Example user ID
        client = GetDataFromServer()
        client.connect()
        lstMusic_favorite = client.sendSignal("GET_FAVORITE_LIST_" + self.userIDDemo)
        print(lstMusic_favorite)
    
        row=0
        for playlist in lstMusic_favorite:
            playlistID=int(playlist["songID"])
            lstMusic = client.sendSignal("GET_MUSIC_LIST")
            for lst in lstMusic:
                musicID=int(lst["id"])
                if playlistID == musicID:
                    self.baihat=baihat.baihat(str(lst["id"]),str(lst["name"]),str(lst["artist"]),str(lst["luotNghe"]),str(lst["img"]),str(lst["mp3"]),self.userIDDemo)
                    self.layout.addWidget(self.baihat,row,0)
                    row+=1   
                        
            
                    




if __name__ == "__main__":
    pl=Favorite_GUI()
