# Form implementation generated from reading ui file 'taikhoancanhan.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import *
from PyQt6.QtGui import *
from GetDataFromServer import GetDataFromServer
class taikhoancanhan(QWidget):
    def __init__(self,userIDDemo,userPassword,name):
        super().__init__()
        self.userIDDemo=userIDDemo
        self.userPassword=userPassword
        self.name=name
        print(userIDDemo)
        self.setupUi()
    def setupUi(self):
        self.setObjectName("Form")
        self.resize(611, 591)
        self.lblUsername = QtWidgets.QLabel(parent=self)
        self.lblUsername.setGeometry(QtCore.QRect(40, 70, 61, 16))
        self.lblUsername.setObjectName("lblUsername")
        self.lblPassword = QtWidgets.QLabel(parent=self)
        self.lblPassword.setGeometry(QtCore.QRect(40, 100, 51, 16))
        self.lblPassword.setObjectName("lblPassword")
        self.txtUsername = QtWidgets.QLineEdit(parent=self)
        self.txtUsername.setGeometry(QtCore.QRect(120, 70, 401, 22))
        self.txtUsername.setObjectName("txtUsername")
        self.txtUsername.setText(self.name)
        self.txtPassword = QtWidgets.QLineEdit(parent=self)
        self.txtPassword.setGeometry(QtCore.QRect(120, 100, 401, 22))
        self.txtPassword.setObjectName("txtPassword")
        self.txtPassword.setText(self.userPassword)
        self.lblTitle = QtWidgets.QLabel(parent=self)
        self.lblTitle.setGeometry(QtCore.QRect(210, 10, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lblTitle.setFont(font)
        self.lblTitle.setObjectName("lblTitle")
        self.btnSua = QtWidgets.QPushButton(parent=self)
        self.btnSua.setGeometry(QtCore.QRect(110, 140, 75, 24))
        self.btnSua.setObjectName("btnSua")
        self.btnSua.clicked.connect(self.update)
        self.btnDangNhap_3 = QtWidgets.QPushButton(parent=self)
        self.btnDangNhap_3.setGeometry(QtCore.QRect(380, 140, 75, 24))
        self.btnDangNhap_3.setObjectName("btnDangNhap_3")

        self.retranslateUi()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.lblUsername.setText(_translate("Form", "Username"))
        self.lblPassword.setText(_translate("Form", "Password"))
        self.lblTitle.setText(_translate("Form", "THÔNG TIN"))
        self.btnSua.setText(_translate("Form", "Sửa"))
        self.btnDangNhap_3.setText(_translate("Form", "Hủy"))

    def update(self):
        client = GetDataFromServer()
        client.connect()
        receive = client.sendUpdateUser("UPDATE_TO_USER_" + self.userIDDemo + "_" + self.txtUsername.text()+ "_" + self.txtPassword.text())
        print(receive)

if __name__ == "__main__":
    tk=taikhoancanhan()
