# Form implementation generated from reading ui file 'CategoryGUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from Category import Category
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import *
from Category_BUS import Category_BUS
class Category_GUI(QWidget):
        def __init__(self):
                super().__init__()
                self.initUI()
        def initUI(self):

                self.resize(670, 550)
                self.content = QtWidgets.QFrame(parent=self)
                self.content.setGeometry(QtCore.QRect(0, 0, 670, 550))
                self.content.setStyleSheet("background-color: #F6F6F6;\n"
        "")
                self.content.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
                self.content.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
                self.content.setObjectName("content")
                self.scrollArea_2 = QtWidgets.QScrollArea(parent=self.content)
                self.scrollArea_2.setGeometry(QtCore.QRect(20, 250, 630, 300))
                self.scrollArea_2.setWidgetResizable(True)
                self.scrollArea_2.setObjectName("scrollArea_2")
                self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
                self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 628, 298))
                self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
                self.cat_table = QtWidgets.QTableWidget(parent=self.scrollAreaWidgetContents_2)
                self.cat_table.setGeometry(QtCore.QRect(0, 0, 630, 300))
                self.cat_table.setObjectName("cat_table")
                self.cat_table.setColumnCount(0)
                self.cat_table.setRowCount(0)
                self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
                self.frame_2 = QtWidgets.QFrame(parent=self.content)
                self.frame_2.setGeometry(QtCore.QRect(20, 20, 630, 210))
                self.frame_2.setStyleSheet("background-color:#FFE2E2 ;")
                self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
                self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
                self.frame_2.setObjectName("frame_2")
                self.label_7 = QtWidgets.QLabel(parent=self.frame_2)
                self.label_7.setGeometry(QtCore.QRect(20, 10, 31, 16))
                font = QtGui.QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.label_7.setFont(font)
                self.label_7.setObjectName("label_7")
                self.label_8 = QtWidgets.QLabel(parent=self.frame_2)
                self.label_8.setGeometry(QtCore.QRect(20, 40, 151, 16))
                font = QtGui.QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.label_8.setFont(font)
                self.label_8.setObjectName("label_8")
                self.txtCatID = QtWidgets.QLineEdit(parent=self.frame_2)
                self.txtCatID.setGeometry(QtCore.QRect(170, 10, 150, 20))
                self.txtCatID.setStyleSheet("background-color: #FFFFFF;\n"
        "")
                self.txtCatID.setObjectName("txtCatID")
                
                self.btnAdd = QtWidgets.QPushButton(parent=self.frame_2)
                self.btnAdd.setGeometry(QtCore.QRect(450, 70, 171, 25))
                self.btnAdd.setStyleSheet("background-color: #ECB159;")
                icon1 = QtGui.QIcon()
                icon1.addPixmap(QtGui.QPixmap("TienNuAdmin/img/plus.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
                self.btnAdd.setIcon(icon1)
                self.btnAdd.setObjectName("btnAdd")
                self.btnUpdate = QtWidgets.QPushButton(parent=self.frame_2)
                self.btnUpdate.setGeometry(QtCore.QRect(450, 100, 171, 25))
                self.btnUpdate.setStyleSheet("background-color: #ECB159;")
                icon2 = QtGui.QIcon()
                icon2.addPixmap(QtGui.QPixmap("TienNuAdmin/img/system-update.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
                self.btnUpdate.setIcon(icon2)
                self.btnUpdate.setObjectName("btnUpdate")
                self.btnDel = QtWidgets.QPushButton(parent=self.frame_2)
                self.btnDel.setGeometry(QtCore.QRect(450, 130, 171, 25))
                self.btnDel.setStyleSheet("background-color: #ECB159;")
                icon3 = QtGui.QIcon()
                icon3.addPixmap(QtGui.QPixmap("TienNuAdmin/img/delete.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
                self.btnDel.setIcon(icon3)
                self.btnDel.setObjectName("btnDel")
                self.btnReFresh = QtWidgets.QPushButton(parent=self.frame_2)
                self.btnReFresh.setGeometry(QtCore.QRect(450, 160, 171, 25))
                self.btnReFresh.setStyleSheet("background-color: #ECB159;")
                icon4 = QtGui.QIcon()
                icon4.addPixmap(QtGui.QPixmap("TienNuAdmin/img/loading-arrow.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
                self.btnReFresh.setIcon(icon4)
                self.btnReFresh.setObjectName("btnReFresh")
                self.txtTitle = QtWidgets.QLineEdit(parent=self.frame_2)
                self.txtTitle.setGeometry(QtCore.QRect(170, 40, 150, 20))
                self.txtTitle.setStyleSheet("background-color: #FFFFFF;\n"
        "")
                self.txtTitle.setObjectName("txtTitle")

                self.retranslateUi()
                
                #------------------Them data vao bang
                self.addDataToTable()
                self.cat_table.itemClicked.connect(self.setDataClicked)
                self.btnAdd.clicked.connect(self.addData)
                self.btnReFresh.clicked.connect(self.reloadTable)
                self.btnUpdate.clicked.connect(self.editData)
                self.btnDel.clicked.connect(self.delData)
                
        
        def retranslateUi(self):
                self.label_7.setText( "ID :")
                self.label_8.setText( "CATEGORY TITLE:")
                self.btnAdd.setText( "ADD")
                self.btnUpdate.setText( "UPDATE")
                self.btnDel.setText("DELETE")
                self.btnReFresh.setText("REFRESH")
        def reloadTable(self):
                self.addDataToTable()
        def addDataToTable(self):
                self.cat_table.clearContents()
                self.cat_table.setRowCount(0)
                self.cat_table.setColumnCount(0)
                self.cat_table.setColumnCount(2)
                lstHead = ['ID', 'Title']
                self.cat_table.setHorizontalHeaderLabels(lstHead)
               
                bus = Category_BUS()
                row_count = len(bus.getData());
                self.cat_table.setRowCount(row_count)
                row = 0;
                for category in  bus.getData():
                        self.cat_table.setItem(row, 0,QTableWidgetItem(str(category.id)))
                        self.cat_table.setItem(row, 1,QTableWidgetItem(str(category.title)))
                        row += 1
        def setDataClicked(self,item):
                row = item.row()
                self.txtCatID.setText(self.cat_table.item(row,0).text())
                self.txtTitle.setText(self.cat_table.item(row,1).text())
        def addData(self):
                cat = Category(0,self.txtTitle.text())
                bus = Category_BUS()
                bus.addData(cat)
                self.reloadTable()
        def editData(self):
                cat = Category(int(self.txtCatID.text()),self.txtTitle.text())
                bus = Category_BUS()
                bus.editData(cat)
                self.reloadTable()
        def delData(self):
                cat = Category(int(self.txtCatID.text()),self.txtTitle.text())
                bus = Category_BUS()
                bus.delData(cat)
                self.reloadTable()