
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import *

from BUS.NhacBUS import NhacBUS
class Nhac_GUI(QWidget):
        def __init__(self):
                super().__init__()
                self.initUI()
        def initUI(self):
                self.resize(670, 550)
                self.content = QtWidgets.QFrame(self)
                self.content.setGeometry(QtCore.QRect(0, 0, 670, 550))
                self.content.setStyleSheet("background-color: #F6F6F6;\n"
        "")
                self.content.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
                self.content.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
                self.content.setObjectName("content")
                self.scrollArea = QtWidgets.QScrollArea(parent=self.content)
                self.scrollArea.setGeometry(QtCore.QRect(20, 250, 630, 300))
                self.scrollArea.setWidgetResizable(True)
                self.scrollArea.setObjectName("scrollArea")
                self.scrollAreaWidgetContents = QtWidgets.QWidget()
                self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 628, 298))
                self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
                self.table = QtWidgets.QTableWidget(parent=self.scrollAreaWidgetContents)
                self.table.setGeometry(QtCore.QRect(0, 0, 630, 300))
                self.table.setObjectName("table")
                self.scrollArea.setWidget(self.scrollAreaWidgetContents)
                self.frame = QtWidgets.QFrame(parent=self.content)
                self.frame.setGeometry(QtCore.QRect(20, 20, 630, 210))
                self.frame.setStyleSheet("background-color:#FFE2E2 ;")
                self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
                self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
                self.frame.setObjectName("frame")
                self.label = QtWidgets.QLabel(parent=self.frame)
                self.label.setGeometry(QtCore.QRect(20, 10, 31, 16))
                font = QtGui.QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.label.setFont(font)
                self.label.setObjectName("label")
                self.label_2 = QtWidgets.QLabel(parent=self.frame)
                self.label_2.setGeometry(QtCore.QRect(20, 40, 111, 16))
                font = QtGui.QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.label_2.setFont(font)
                self.label_2.setObjectName("label_2")
                self.label_3 = QtWidgets.QLabel(parent=self.frame)
                self.label_3.setGeometry(QtCore.QRect(20, 70, 111, 16))
                font = QtGui.QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.label_3.setFont(font)
                self.label_3.setObjectName("label_3")
                self.label_4 = QtWidgets.QLabel(parent=self.frame)
                self.label_4.setGeometry(QtCore.QRect(20, 100, 111, 16))
                font = QtGui.QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.label_4.setFont(font)
                self.label_4.setObjectName("label_4")
                self.label_5 = QtWidgets.QLabel(parent=self.frame)
                self.label_5.setGeometry(QtCore.QRect(20, 130, 111, 16))
                font = QtGui.QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.label_5.setFont(font)
                self.label_5.setObjectName("label_5")
                self.label_6 = QtWidgets.QLabel(parent=self.frame)
                self.label_6.setGeometry(QtCore.QRect(20, 160, 111, 16))
                font = QtGui.QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.label_6.setFont(font)
                self.label_6.setObjectName("label_6")
                self.txtID = QtWidgets.QLineEdit(parent=self.frame)
                self.txtID.setGeometry(QtCore.QRect(130, 10, 150, 20))
                self.txtID.setStyleSheet("background-color: #FFFFFF;\n"
        "")
                self.txtID.setObjectName("txtID")
                self.txtName = QtWidgets.QLineEdit(parent=self.frame)
                self.txtName.setGeometry(QtCore.QRect(130, 70, 150, 20))
                self.txtName.setStyleSheet("background-color: #FFFFFF;\n"
        "")
                self.txtName.setObjectName("txtName")
                self.txtArtist = QtWidgets.QLineEdit(parent=self.frame)
                self.txtArtist.setGeometry(QtCore.QRect(130, 100, 150, 20))
                self.txtArtist.setStyleSheet("background-color: #FFFFFF;\n"
        "")
                self.txtArtist.setObjectName("txtArtist")
                self.txtimg = QtWidgets.QLineEdit(parent=self.frame)
                self.txtimg.setGeometry(QtCore.QRect(130, 130, 150, 20))
                self.txtimg.setStyleSheet("background-color: #FFFFFF;\n"
        "")
                self.txtimg.setObjectName("txtimg")
                self.txtmp3 = QtWidgets.QLineEdit(parent=self.frame)
                self.txtmp3.setGeometry(QtCore.QRect(130, 160, 150, 20))
                self.txtmp3.setStyleSheet("background-color: #FFFFFF;\n"
        "")
                self.txtmp3.setObjectName("txtmp3")
                self.cbCate = QtWidgets.QComboBox(parent=self.frame)
                self.cbCate.setGeometry(QtCore.QRect(130, 40, 151, 22))
                self.cbCate.setObjectName("cbCate")
                self.imgLB = QtWidgets.QLabel(parent=self.frame)
                self.imgLB.setGeometry(QtCore.QRect(300, 10, 101, 101))
                self.imgLB.setStyleSheet("background-color: #fff;")
                self.imgLB.setObjectName("imgLB")
                self.btnIMG = QtWidgets.QPushButton(parent=self.frame)
                self.btnIMG.setGeometry(QtCore.QRect(280, 130, 31, 20))
                self.btnIMG.setText("")
                icon = QtGui.QIcon()
                icon.addPixmap(QtGui.QPixmap("img/photo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
                self.btnIMG.setIcon(icon)
                self.btnIMG.setObjectName("btnIMG")
                self.btnMusic = QtWidgets.QPushButton(parent=self.frame)
                self.btnMusic.setGeometry(QtCore.QRect(280, 160, 31, 21))
                self.btnMusic.setText("")
                icon1 = QtGui.QIcon()
                icon1.addPixmap(QtGui.QPixmap("img/music-notes.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
                self.btnMusic.setIcon(icon1)
                self.btnMusic.setObjectName("btnMusic")
                self.btnPlay = QtWidgets.QPushButton(parent=self.frame)
                self.btnPlay.setGeometry(QtCore.QRect(20, 180, 31, 21))
                self.btnPlay.setText("")
                icon2 = QtGui.QIcon()
                icon2.addPixmap(QtGui.QPixmap("img/play-button.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
                self.btnPlay.setIcon(icon2)
                self.btnPlay.setObjectName("btnPlay")
                self.btnFind = QtWidgets.QPushButton(parent=self.frame)
                self.btnFind.setGeometry(QtCore.QRect(600, 40, 21, 21))
                self.btnFind.setText("")
                icon3 = QtGui.QIcon()
                icon3.addPixmap(QtGui.QPixmap("img/search.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
                self.btnFind.setIcon(icon3)
                self.btnFind.setObjectName("btnFind")
                self.cbFind = QtWidgets.QComboBox(parent=self.frame)
                self.cbFind.setGeometry(QtCore.QRect(450, 10, 171, 22))
                self.cbFind.setObjectName("cbFind")
                self.txtFind = QtWidgets.QLineEdit(parent=self.frame)
                self.txtFind.setGeometry(QtCore.QRect(450, 40, 150, 20))
                self.txtFind.setStyleSheet("background-color: #FFFFFF;\n"
        "")
                self.txtFind.setObjectName("txtFind")
                self.addBtn = QtWidgets.QPushButton(parent=self.frame)
                self.addBtn.setGeometry(QtCore.QRect(450, 70, 171, 25))
                self.addBtn.setStyleSheet("background-color: #ECB159;")
                icon4 = QtGui.QIcon()
                icon4.addPixmap(QtGui.QPixmap("img/plus.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
                self.addBtn.setIcon(icon4)
                self.addBtn.setObjectName("addBtn")
                self.updateBtn = QtWidgets.QPushButton(parent=self.frame)
                self.updateBtn.setGeometry(QtCore.QRect(450, 100, 171, 25))
                self.updateBtn.setStyleSheet("background-color: #ECB159;")
                icon5 = QtGui.QIcon()
                icon5.addPixmap(QtGui.QPixmap("img/system-update.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
                self.updateBtn.setIcon(icon5)
                self.updateBtn.setObjectName("updateBtn")
                self.deleteBtn = QtWidgets.QPushButton(parent=self.frame)
                self.deleteBtn.setGeometry(QtCore.QRect(450, 130, 171, 25))
                self.deleteBtn.setStyleSheet("background-color: #ECB159;")
                icon6 = QtGui.QIcon()
                icon6.addPixmap(QtGui.QPixmap("img/delete.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
                self.deleteBtn.setIcon(icon6)
                self.deleteBtn.setObjectName("deleteBtn")
                self.refreshBtn = QtWidgets.QPushButton(parent=self.frame)
                self.refreshBtn.setGeometry(QtCore.QRect(450, 160, 171, 25))
                self.refreshBtn.setStyleSheet("background-color: #ECB159;")
                icon7 = QtGui.QIcon()
                icon7.addPixmap(QtGui.QPixmap("img/loading-arrow.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
                self.refreshBtn.setIcon(icon7)
                self.refreshBtn.setObjectName("refreshBtn")

                self.retranslateUi()
                
                #---------------------------------------
                self.addDataToTable()

        
        def retranslateUi(self):
                self.label.setText( "ID :")
                self.label_2.setText("CATEGORY:")
                self.label_3.setText("NAME: ")
                self.label_4.setText( "ARTIST: ")
                self.label_5.setText( "IMG SOURCE: ")
                self.label_6.setText( "MP3 SOURCE: ")
                self.imgLB.setText( "imgHere")
                self.addBtn.setText( "ADD")
                self.updateBtn.setText("UPDATE")
                self.deleteBtn.setText( "DELETE")
                self.refreshBtn.setText( "REFRESH")
        def addDataToTable(self):
                self.table.setColumnCount(6)
                lstHead = ["ID", "CategoryID", "Name", "Artist", "Img source","MP3 source"]
                self.table.setHorizontalHeader(lstHead)
                bus = NhacBUS()
                row_count = len(bus.getData());
                self.table.setRowCount(row_count)
                row = 0;
                for music in  bus.getData():
                        self.table.setItem(row, 0,str(music.id))
                        self.table.setItem(row, 1,str(music.catID))
                        self.table.setItem(row, 2,str(music.name))
                        self.table.setItem(row, 3,str(music.artist))
                        self.table.setItem(row, 4,str(music.img))
                        self.table.setItem(row, 5,str(music.mp3))
                        row += 1
                
                
