# Form implementation generated from reading ui file 'ServerGUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


import datetime
from PyQt6 import QtCore, QtGui, QtWidgets
import sys
from PyQt6.QtWidgets import *
from PyQt6.QtGui import *
from PyQt6.QtCore import Qt
from SocketServer import SocketServer

class ServerGUI(QWidget):
    def __init__(self):
        super().__init__();
        self.server = SocketServer()
        self.initUI()
    def initUI(self):
        self.resize(670, 550)
        self.content = QtWidgets.QFrame(self)
        self.content.setGeometry(QtCore.QRect(0, 0, 670, 550))
        self.content.setStyleSheet("background-color: #F6F6F6;\n"
"")
        self.content.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.content.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.content.setObjectName("content")
        
        self.btnStartServer = QtWidgets.QPushButton(parent=self.content)
        self.btnStartServer.setGeometry(QtCore.QRect(480, 10, 171, 25))
        self.btnStartServer.setStyleSheet("background-color: green;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("TienNuAdmin/img/play.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnStartServer.setIcon(icon)
        self.btnStartServer.setObjectName("btnStartServer")
        
        self.btnStop = QtWidgets.QPushButton(parent=self.content)
        self.btnStop.setGeometry(QtCore.QRect(480, 10, 171, 25))
        self.btnStop.setStyleSheet("background-color: red;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("TienNuAdmin/img/stop-button.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnStop.setIcon(icon2)
        self.btnStop.setObjectName("btnStop")
        self.btnStop.setVisible(False)
        
        self.scrollArea = QtWidgets.QScrollArea(parent=self.content)
        self.scrollArea.setGeometry(QtCore.QRect(19, 66, 631, 471))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 629, 469))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.message = QtWidgets.QTextEdit(parent=self.scrollAreaWidgetContents)
        self.message.setGeometry(QtCore.QRect(-7, -4, 641, 481))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.message.setFont(font)
        self.message.setObjectName("message")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label = QtWidgets.QLabel(parent=self.content)
        self.label.setGeometry(QtCore.QRect(20, 35, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        #Dat lenh cho button
        self.btnStartServer.clicked.connect(self.startServer)
        self.btnStop.clicked.connect(self.stopServer)
        self.server.message_received.connect(self.addMessage)
        self.retranslateUi()

    def retranslateUi(self):
        self.btnStartServer.setText("START SERVER")
        self.label.setText( "SERVER ACTIVITIES")
        self.btnStop.setText("STOP SERVER")

    def startServer(self):
        self.btnStartServer.setVisible(False)
        self.btnStop.setVisible(True)
        self.server.start()
        self.addMessage("Start Server")
        
    def stopServer(self):
        self.server.stop()
        self.btnStop.setVisible(False)
        self.btnStartServer.setVisible(True)
        self.addMessage("Stop Server")
    def addMessage(self,message):
        date = datetime.datetime.now().date().__str__()
        time = datetime.datetime.now().strftime("%H:%M:%S").__str__()
        old_message = self.message.toPlainText()
        self.message.append( date + "|" + time + ": " + message)
        